### ISSUE TITLE
Weighing factors of Hahn window

### ISSUE THREAD

**Issue by Chris2B91** [kosme/arduinoFFT#100]
Hello,

in the windowing function (within arduinoFFT.cpp), the weighing factors for Hahn and Hamming windows are computed as follows

      case FFTWindow::Hamming: // hamming
        weighingFactor = 0.54 - (0.46 * cos(twoPi * ratio));
        break;
      case FFTWindow::Hann: // hann
        weighingFactor = 0.54 * (1.0 - cos(twoPi * ratio));
        break;

But looking at this page (https://en.wikipedia.org/wiki/Window_function), I am wondering whether the correct computation should be:
Hamming:  `weighingFactor = 25 / 46 * (1 - cos(twoPi * ratio))`
Hahn: `weighingFactor = 0.5 * (1 - cos(twoPi * ratio))`

Am I right, or did I get something wrong ?

Best regards

**Comment by kosme** [comment]
You are right about the Hann windowing. Thanks for pointing this out. I just traced its origin back to the original library implementation.
