### ISSUE TITLE
Forward FFT for complex inputs

### ISSUE THREAD

**Issue by thaumatichthys** [kosme/arduinoFFT#105]
Sorry if I am misunderstanding, but in your FFT code, you only do bit reversal for the real inputs when doing forward FFT. I assume that you do this since normally you only have real inputs, and the imaginary part is mostly just an output, but when there are complex inputs, it computes the FFT wrongly.

**Comment by kosme** [comment]
This should be solved on version 2.0.4. Any feedback is appreciated.
