### ISSUE TITLE
A very basic problem

### ISSUE THREAD

**Issue by zachosrias** [kosme/arduinoFFT#19]
Hey
I'm very new to all this electronics stuff, im not as technically inclined as i though it seems (compared to all o' y'all ;D ) i dont understand how the hell i add the file to my arduino installation, that will make the error message go away, the one that contains the information that my computer cant find in its library. 

you know the one that will stop this error:

/Users/zachos/Documents/Arduino/whistler/whistler.ino:1:68: fatal error: arduinoFFT.h: No such file or directory
 #include "arduinoFFT.h" // From https://github.com/kosme/arduinoFFT
                                                                    ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.

btw im doing this on a macbook (don't judge me) so it may be different on my end than on yours...?
ive tried to open the folder the error refers to (/Users/zachos/Documents/Arduino/whistler) and just dropping the the README.md.webloc (_https://github.com/kosme/arduinoFFT/blob/master/README.md_) in there (ive also tried the version 1.4(_https://github.com/kosme/arduinoFFT/commit/d8c22a897e637bb1719dfbef84f83a279c634eef_)), but it constantluy judt shows up as a link to the webpage, i think that might have something to do with whythe arduino cant use it even though it is there, but how do i get it in there so it can use it?

I'm at my wits end, i dont really have anyone else to turn to for help right now so will you please help me?

**Comment by kosme** [comment]
You need to use the Arduino Library Manager to install the arduinoFFT library. That will solve your compilation problem.
