### ISSUE TITLE
Is there any way to get the Arduino IDE in the spectrum layout

### ISSUE THREAD

**Issue by zzxjl1** [kosme/arduinoFFT#25]
The serial output seems out of order in Arduino IDE's chart function, is there any way to struct the output?

**Comment by kosme** [comment]
That is a quite broad question. What code are you running and how do you want the output to be structured?

**Comment by zzxjl1** [comment]
I'm running the third example code

**Comment by zzxjl1** [comment]
and i want it to output like bar chart
