### ISSUE TITLE
Need new method

### ISSUE THREAD

**Issue by i4things** [kosme/arduinoFFT#27]
I need a new method e.g. void MajorPeak(double & f, double & v);

which returns not only the peak interpolated frequency but also the peak interpolated value...

can you add something like this ?

the reason is that to calculate the sea wave height :

sea wave height = Elevation spectrum Sz(f) =  acceleration spectrum Sa(f) / (2*pi*f)^4

using the double MajorPeak(); I get the f but to get the acceleration spectrum Sa(f) I need the interpolated value also... 

if I'm not mistaken btw :)

**Comment by kosme** [comment]
The method was created on the most recent commit.
