### ISSUE TITLE
would like latest code in a 'release'

### ISSUE THREAD

**Issue by bradanlane** [kosme/arduinoFFT#29]
Great library. I am using the ArduinoFFT library in a PlatformIO project. PlatformIO will only load releases. If the latest code is stable, it would help me if it were marked as a release (1.5 or 1.4.??). Thank you.

**Comment by bradanlane** [comment]
ignore. found out that PlatformIO has a syntax for using git URL direction

**Comment by kosme** [comment]
Thanks for pointing this out. It is done now.

**Comment by bradanlane** [comment]
Much appreciate your work.
