### ISSUE TITLE
For FFT.MajorPeak would like to see magnitude along with frequency.

### ISSUE THREAD

**Issue by atuline** [kosme/arduinoFFT#30]
A major peak at 400Hz with a magnitude of 200 is a LOT different than a major peak at 1KHz with a magnitude of 20.

**Comment by kosme** [comment]
As far as I understand your request, that is exactly what happens on example FFT_05.

**Comment by atuline** [comment]
You are right. Thank you, I missed that when I ran FFT_05 earlier. Ended up focusing on FFT_03.
