### ISSUE TITLE
The calculated peak frequency is half the actual signal frequency.

### ISSUE THREAD

**Issue by JuriShalkin** [kosme/arduinoFFT#36]
I use the FFT to analyze the sound spectrum on ESP32. Sampling frequency of 40000 Hz, the number of samples is 512. I use the sound signal to calibrate and verify the operation. In doing so, I get the calculated peak frequency half that of the actual signal frequency. The spectrogram looks like a signal with half the frequency.

**Comment by kosme** [comment]
What frequency are you expecting to get and which one are you getting?

**Comment by JuriShalkin** [comment]
For example, I give a sound signal with a frequency of 8000 Hz, I get about 4000 Hz.

**Comment by JuriShalkin** [comment]
My source https://github.com/JuriShalkin/T-Watch-FFT-Waterfall

**Comment by JuriShalkin** [comment]
Sorry, this is my mistake. I used the wrong code to read data from the ADC.
