### ISSUE TITLE
Change request double type to float

### ISSUE THREAD

**Issue by mrguen** [kosme/arduinoFFT#45]
Thanks for this great library. I am now using it on STM32 and the double type is 64 bits so it takes a lot of memory when using the actual "double" type that is used everywhere. 

I changed them to float. This is much more convenient and does not visibly reduce  the precision. For usual Arduino boards like the UNO float and double datatypes are equivalent 32 bits data.

**Comment by HorstBaerbel** [comment]
See the [develop branch](https://github.com/kosme/arduinoFFT/tree/develop) and / or pull request #42.

**Comment by mrguen** [comment]
@HorstBaerbel Thanks. I had the dev branch working well, using a 4096 values float array on my STM32F401RCT6 with Arduino Core STM32

**Comment by HorstBaerbel** [comment]
Damn. Should be fixed in pull request #50.

**Comment by mrguen** [comment]
@HorstBaerbel 

Thanks for the dev version. I am not testing it on an Atmega1284 and saw these:

1) I think there is a little error in the examples. When creating a synthetic wave
  float cycles = (((samples-1) * signalFrequency) / samplingFrequency); //Number of signal cycles that the sampling will read

should be:  
float cycles = (((samples) * signalFrequency) / samplingFrequency); //Number of signal cycles that the sampling will read

The duration of the sampling is indeed = samples / samplingFrequency either you index them from 0 or 1. 

2) Also I wonder if it is normal to have a peak at "0 H", even after removing the DC component?

**Comment by HorstBaerbel** [comment]
I don't know as I'm not the maintainer. I'd suggest you open a new issue when you're sure these things are errors, as they have nothing to do with this one. You can also directly point to source code lines using the web interface: Navigate to the file, click the line number, click the "..." menu and then choose the option you'd like, e.g. "create permalink" or even "new issue".

**Comment by mrguen** [comment]
Ok, I will do that.
