### ISSUE TITLE
Storage issues with sample sizes over 128

### ISSUE THREAD

**Issue by kieferlord** [kosme/arduinoFFT#46]
Hello,

Your library works great for sample sizes of 128 and below, but when I try anything above that in order to obtain a better resolution, I have storage issues. The specific error message is:

Global variables use 2278 bytes (111%) of dynamic memory, leaving -230 bytes for local variables. Maximum is 2048 bytes.

I have tried moving the vReal and vImag arrays into the void loop() so they would no longer be considered global variables, but this caused a bunch of other problems (crazy things printing, like backwards question marks, etc.). Do you have any suggestions? Thanks.

**Comment by kosme** [comment]
That is a hardware related issue. If you want to store more than 128 samples, you need a device with more RAM available.

**Comment by HorstBaerbel** [comment]
You could try switching to float values. See the [develop branch](https://github.com/kosme/arduinoFFT/tree/develop) and / or pull request #42.
