### ISSUE TITLE
ESP32 and SPH0645LM4H

### ISSUE THREAD

**Issue by NicolaRusso** [kosme/arduinoFFT#5]
Hi!
Is possible to use the lib with ESP32 and a SPH0645LM4H mic (https://www.adafruit.com/product/3421)? 
Thank you!

**Comment by kosme** [comment]
It has been tested to work on the ESP8266 so I don't see why it wouldn't
work on the ESP32.

**Comment by kosme** [comment]
Also, the question is quite hardware specific to be considered an issue so this will be closed.
