### ISSUE TITLE
Simulated waveform little bug

### ISSUE THREAD

**Issue by mrguen** [kosme/arduinoFFT#52]
I think there is a little error in the examples. When creating a synthetic wave

https://github.com/kosme/arduinoFFT/blob/4011ca2749127a65af59cdef3fb9ab94a7945dd7/Examples/FFT_01/FFT_01.ino#L62

should be:
float cycles = (((samples) * signalFrequency) / samplingFrequency); //Number of signal cycles that the sampling will read

The duration of the sampling is indeed = samples / samplingFrequency either you index them from 0 or 1.

**Comment by kosme** [comment]
Thanks for pointing that out. It has been fixed on v1.6.2
