### ISSUE TITLE
Detecting wrong major Peak values at low frequencies

### ISSUE THREAD

**Issue by mrguen** [kosme/arduinoFFT#54]
Hello,

Thanks for the good work. Of course the FFT is an approximation with a couple of error sources. Here I have a problem to detect low fundamental frequencies.

I am sampling a sinusoidal signal from a function generator at Fs = 16 KHz. When the  signal frequency is under approximately 500 Hz, the result of the majorPeak() computation are wrong. The lower limit of the frequency detection depends on the window used.  
So I tested all the windows with frequencies  100, 150, 200, 250, 300, 400, 500, 600, 1000, 2000, 5000, 10000 and 15000  Hz 

I am using the dev branch and arrays of  float values.

Results:

|   |   |   |
|---|---|---|
| Windowing |  Lower limit Hz  |  Precision above the limit  |
|  Without | 250  |  worse  | 
| Rectangle  | 250  |  worse | 
| Hamming  |  400 |  good | 
| Hann  |  400 |  best of all | 
| Triangle  | 400  |  average  | 
| Nuttall  | 600   |  average | 
| Blackman  |  600 |  average | 
| Blackman Nuttall  | 600  | average  | 
| Blackman Harris  | 600  | average  | 
| Flt top  | 600  |  over estimated | 
| Welch  | 600  | average  | 

My problem is that I don't know how to eliminate a result that would be wrong when the signal is under the lower limit. For example it is a 100 Hz signal and I get inconsistent and wrong values in the Khz range.

How could we check if the result is wrong? Is there a way to study the spectre to detect this? Or another way to cope with this?

**Comment by DrDiettrich** [comment]
Am 11.08.2020 um 11:33 schrieb Thierry GUENNOU:

> Thanks for the good work. Of course the FFT is an approximation with a couple of error sources. Here I have a problem to detect low fundamental frequencies.
> 
> I am sampling a sinusoidal signal from a function generator at Fs = 16 KHz.

Then measure an exact number of waves to satisfy the seamless 
requirement - no windowing required then!

DoDi

**Comment by mrguen** [comment]
@DrDiettrich  Do you mean skip to frequency counting instead of FT?

**Comment by DrDiettrich** [comment]
Am 11.08.2020 um 17:19 schrieb Thierry GUENNOU:
> @DrDiettrich  Do you mean skip to frequency counting instead of FFT?

Depends on what you want to achieve. You can determine the base 
frequency first, then switch to FFT for detection of harmonics.

DoDi

**Comment by mrguen** [comment]
Yes of course but we are talking about the FFT library here. I wonder if 1) there might be a bug 2) we can do something to measure the low frequency component. 3) In consequence I also realize that it is not possible to use this to compute a full spectrum, unless the frequencies under 600 Hz don't mind which is very doubtfull for anyone looking for audio spectral analysis. I have no idea if this can be better or not.

**Comment by mrguen** [comment]
@DrDiettrich 

Sorry, there was nothing wrong with the detection of MajorPeak. I was in fact sampling @ 600 KHz so there were not enough periods in the samples to compute the fequencies
