### ISSUE TITLE
FFT_01 Example

### ISSUE THREAD

**Issue by sid333** [kosme/arduinoFFT#6]
Hi there,
I'm a beginner with Arduino and github but I tried implementing your FFT_01 example on an Arduino M0. It worked fine initially. I then tried setting the code to run in a loop by commenting out the while(1) condition and uncommenting the delay(2000) condition. I have noticed that for some reason the first loop iteration calculates the frequency correctly but subsequent iterations produce the same incorrect result. I have not changed anything else about the code other than changing Serial.xxxx into SerialUSB.xxxx functions so it is compatible with the Arduino M0.
Could you please advise me if I am using the code incorrectly or if there is some issue
Thanks!!

**Comment by kosme** [comment]
Thanks for the report. I'll check it out tonight.

**Comment by kosme** [comment]
Fixed on the most recent commit.
