### ISSUE TITLE
software wdt reset occurs every time when using nodemcu esp module

### ISSUE THREAD

**Issue by mlanandnair** [kosme/arduinoFFT#7]
Hi sir , 
I have a nodemcu esp module and i have tried fft using your library . Everytime when comes at the while(1) infinite loop, module goes through a software wdt reset . As I have read in the esp documentation they had specified that a while(1) statement can trigger a wdt reset . I have tried uncommenting while(1) statement which cause frequency keep on iteration and causing overflow .I have just used the example3 in the fft library . I am doing something wrong sir . Can you please help me out?

**Comment by kosme** [comment]
The overflow part is fixed on the most recent commit. The wdt reset is an issue specific of the nodemcu module. This seems to fix that [Link](https://community.blynk.cc/t/solved-esp8266-nodemcu-v1-0-and-wdt-resets/7047/13)
