### ISSUE TITLE
Implement C++ template

### ISSUE THREAD

**Issue by blazoncek** [kosme/arduinoFFT#74]
Sometimes double precision is not necessary and may just make computations slow.

It would be nice if the library was made using template so that both double and float could be used.

If this is not possible (due to compatibility with C) then a float version would also work in addition to double.

**Comment by blaz-r** [comment]
This is implemented on develop branch. It also includes some other optimizations.

It'd be nice to have that on main, but it's probably not due to compatibility.

**Comment by blazoncek** [comment]
Thanks for pointing that out.
Still there are non-float constants and functions used there. Changing those may further optimise the execution and storage used.

**Comment by kosme** [comment]
@blazoncek Do you consider that the current code on the main branch accomplishes what you are pointing out??

**Comment by blazoncek** [comment]
Hi. Thanks for the update but I fail to see templates in main branch, though I can see template implementation in the develop branch.

I have one more remark. There are quite a few floating point constants used in the code. Unless those are suffixed by `f` those are stored as double precision regardless of the type used in template. I would recommend to suffix at least those that do not benefit of the precision to reduce the code size.

**Comment by blazoncek** [comment]
Seems like this can be closed with v2.
Thank you for the effort.
