### ISSUE TITLE
Memory limit exceeds for samples = 256 in Arduino Uno

### ISSUE THREAD

**Issue by ashish28ranjan** [kosme/arduinoFFT#9]
When using samples = 256, the Global Variables use more than 2048 bytes which is not allowed in Arduino Uno (ATmega328p).
I want to calculate DFT of only real signals (e.g. ADC input). Could it be possible to optimize the code for only real signals?
I tried to do it myself but came to the conclusion that the code was already immensely optimized for space.

**Comment by kosme** [comment]
Yeah, i know of that problem. (256 samples not fitting into Arduino RAM) Unfortunately, FFT depends on the imaginary part for doing the math. Maybe you could try looking for a FHT algorithm, that one only uses the real part of the signals. Another option is changing the hardware for something with more RAM. I have seen the code working on esp8266 and pic32 boards.

**Comment by ashish28ranjan** [comment]
Thanks bro! I would look into it.

**Comment by akshulg** [comment]
128 number of samples not enough to calculate fft of real signals?

**Comment by kosme** [comment]
Mostly it depends on how stable is the signal you are measuring. If it is
stable enough, 128 samples is enough if you choose the correct sampling
frequency (around 2.5 times your maximum expected frequency) Having a
really high number of samples and/or sampling at a really high frequency will
not provide an important increase on accuracy as the relationship is
logarithmic. Also, increasing the number of samples increases the
processing time.
